generator = { tableDefinition };
tableDefinition = "table:" "(" diceNotation ")" text "[" ident "]" newline option { newline option };
diceNotation = ? dice notation ?;
newline = ? all newline characters ?;